# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
encoding: utf-8
lang: en-US
url: 'https://wonmanlee.com'
baseurl: ''
title: 'wonmanlee'
description: 'Exploring the basics in C#'
permalink: pretty
logo: "https://en.gravatar.com/userimage/34757508/c17ed5710cb28e8e3ee7801113d11b06.png"
disqus: "wonmanlee"
email: "wonmanlee@gmail.com"
google_analytics: "UA-149261153-1"

# Pagination
paginate: 5
paginate_path: blog/page:num
twitter: 
  username: wonmanlee
author: WonmanLee
social: 
  name: Wonman Lee
  links: 
    - https://twitter.com/wonmanlee
    - https://www.linkedin.com/in/wonmanlee
    - https://github.com/wonmanlee

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Search
  url: /search/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  email: mailto:wonmanlee@gmail.com    
  LinkedIn: https://www.linkedin.com/in/wonmanlee
  GitHub: https://github.com/wonmanlee
  link: https://bit.ly/wonmanlee
  RSS: /feed.xml    