# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://wonmanlee.com'
baseurl: ''
title: 'wonmanlee'
description: 'Exploring the basics in C#'
permalink: pretty
logo: "https://en.gravatar.com/userimage/34757508/c17ed5710cb28e8e3ee7801113d11b06.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Search
  url: /search/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  email: mailto:wonmanlee@gmail.com    
  LinkedIn: https://www.linkedin.com/in/wonmanlee
  GitHub: https://github.com/wonmanlee
  link: https://bit.ly/wonmanlee
  RSS: /feed.xml    

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true  